export const starting_position = {
  1: [
    {position: [1,1], piece: {pieceType: null, pieceImgPath: null}},
    {position: [1,2], piece: {pieceType: null, pieceImgPath: null}},
    {position: [1,3], piece: {pieceType: null, pieceImgPath: null}},
    {position: [1,3], piece: {pieceType: null, pieceImgPath: null}},
    {position: [1,4], piece: {pieceType: null, pieceImgPath: null}},
    {position: [1,5], piece: {pieceType: null, pieceImgPath: null}} ],
  2: [
    {position: [2,1], piece: {pieceType: 'pawn', pieceImgPath: black.pawn}},
    {position: [2,2], piece: {pieceType: null, pieceImgPath: null}},
    {position: [2,3], piece: {pieceType: null, pieceImgPath: null}},
    {position: [2,4], piece: {pieceType: null, pieceImgPath: null}},
    {position: [2,5], piece: {pieceType: null, pieceImgPath: null}},
    {position: [2,6], piece: {pieceType: null, pieceImgPath: null}},
    {position: [2,7], piece: {pieceType: 'pawn', pieceImgPath: white.pawn}} ],
  3: [
    {position: [3,1], piece: {pieceType: 'rook', pieceImgPath: black.rook}},
    {position: [3,2], piece: {pieceType: 'pawn', pieceImgPath: black.pawn}},
    {position: [3,3], piece: {pieceType: null, pieceImgPath: null}},
    {position: [3,4], piece: {pieceType: null, pieceImgPath: null}},
    {position: [3,5], piece: {pieceType: null, pieceImgPath: null}},
    {position: [3,6], piece: {pieceType: null, pieceImgPath: null}},
    {position: [3,7], piece: {pieceType: 'pawn', pieceImgPath: white.pawn}},
    {position: [3,8], piece: {pieceType: 'rook', pieceImgPath: white.rook}} ],
  4: [
    {position: [4,1], piece: {pieceType: 'b_knight', pieceImgPath: black.knight}},
    {position: [4,2], piece: {pieceType: null, pieceImgPath: null}},
    {position: [4,3], piece: {pieceType: 'pawn', pieceImgPath: black.pawn}},
    {position: [4,4], piece: {pieceType: null, pieceImgPath: null}},
    {position: [4,5], piece: {pieceType: null, pieceImgPath: null}},
    {position: [4,6], piece: {pieceType: null, pieceImgPath: null}},
    {position: [4,7], piece: {pieceType: 'pawn', pieceImgPath: white.pawn}},
    {position: [4,8], piece: {pieceType: null, pieceImgPath: null}},
    {position: [4,9], piece: {pieceType: 'knight', pieceImgPath: white.pawn}} ],
  5: [
    {position: [5,1], piece: {pieceType: 'king', pieceImgPath: black.king}},
    {position: [5,2], piece: {pieceType: null, pieceImgPath: null}},
    {position: [5,3], piece: {pieceType: null, pieceImgPath: null}},
    {position: [5,4], piece: {pieceType: 'pawn', pieceImgPath: black.pawn}},
    {position: [5,5], piece: {pieceType: null, pieceImgPath: null}},
    {position: [5,6], piece: {pieceType: null, pieceImgPath: null}},
    {position: [5,7], piece: {pieceType: 'pawn', pieceImgPath: white.pawn}},
    {position: [5,8], piece: {pieceType: null, pieceImgPath: null}},
    {position: [5,9], piece: {pieceType: null, pieceImgPath: null}},
    {position: [5,10], piece: {pieceType: 'king', pieceImgPath: white.king}} ],
  6: [
    {position: [6,1], piece: {pieceType: 'queen', pieceImgPath: black.bishop}},
    {position: [6,2], piece: {pieceType: 'queen', pieceImgPath: black.bishop}},
    {position: [6,3], piece: {pieceType: 'queen', pieceImgPath: black.bishop}},
    {position: [6,4], piece: {pieceType: null, pieceImgPath: null}},
    {position: [6,5], piece: {pieceType: 'pawn', pieceImgPath: black.pawn}},
    {position: [6,6], piece: {pieceType: null, pieceImgPath: null}},
    {position: [6,7], piece: {pieceType: 'pawn', pieceImgPath: white.pawn}},
    {position: [6,8], piece: {pieceType: null, pieceImgPath: null}},
    {position: [6,9], piece: {pieceType: 'bishop', pieceImgPath: white.bishop}},
    {position: [6,10], piece: {pieceType: 'bishop', pieceImgPath: white.bishop}},
    {position: [6,11], piece: {pieceType: 'bishop', pieceImgPath: white.bishop}} ],
  7: [
    {position: [7,1], piece: {pieceType: 'queen', pieceImgPath: black.queen}},
    {position: [7,2], piece: {pieceType: null, pieceImgPath: null}},
    {position: [7,3], piece: {pieceType: null, pieceImgPath: null}},
    {position: [7,4], piece: {pieceType: 'pawn', pieceImgPath: black.pawn}},
    {position: [7,5], piece: {pieceType: null, pieceImgPath: null}},
    {position: [7,6], piece: {pieceType: null, pieceImgPath: null}},
    {position: [7,7], piece: {pieceType: null, pieceImgPath: null}},
    {position: [7,8], piece: {pieceType: 'pawn', pieceImgPath: white.pawn}},
    {position: [7,9], piece: {pieceType: null, pieceImgPath: null}},
    {position: [7,10], piece: {pieceType: 'queen', pieceImgPath: white.queen}} ],
  8: [
    {position: [8,1], piece: {pieceType: 'b_knight', pieceImgPath: black.knight}},
    {position: [8,2], piece: {pieceType: null, pieceImgPath: null}},
    {position: [8,3], piece: {pieceType: 'pawn', pieceImgPath: black.pawn}},
    {position: [8,4], piece: {pieceType: null, pieceImgPath: null}},
    {position: [8,5], piece: {pieceType: null, pieceImgPath: null}},
    {position: [8,6], piece: {pieceType: null, pieceImgPath: null}},
    {position: [8,7], piece: {pieceType: 'pawn', pieceImgPath: white.pawn}},
    {position: [8,8], piece: {pieceType: null, pieceImgPath: null}},
    {position: [8,9], piece: {pieceType: 'knight', pieceImgPath: white.knight}} ],
  9: [
    {position: [9,1], piece: {pieceType: 'rook', pieceImgPath: black.rook}},
    {position: [9,2], piece: {pieceType: 'pawn', pieceImgPath: black.pawn}},
    {position: [9,3], piece: {pieceType: null, pieceImgPath: null}},
    {position: [9,4], piece: {pieceType: null, pieceImgPath: null}},
    {position: [9,5], piece: {pieceType: null, pieceImgPath: null}},
    {position: [9,6], piece: {pieceType: null, pieceImgPath: null}},
    {position: [9,7], piece: {pieceType: 'pawn', pieceImgPath: white.pawn}},
    {position: [9,8], piece: {pieceType: 'rook', pieceImgPath: white.rook}} ],
  10: [
    {position: [10,1], piece: {pieceType: 'pawn', pieceImgPath: black.pawn}},
    {position: [10,2], piece: {pieceType: null, pieceImgPath: null}},
    {position: [10,3], piece: {pieceType: null, pieceImgPath: null}},
    {position: [10,4], piece: {pieceType: null, pieceImgPath: null}},
    {position: [10,5], piece: {pieceType: null, pieceImgPath: null}},
    {position: [10,6], piece: {pieceType: null, pieceImgPath: null}},
    {position: [10,7], piece: {pieceType: 'pawn', pieceImgPath: white.pawn}} ],
  11: [
    {position: [11,1], piece: {pieceType: null, pieceImgPath: null}},
    {position: [11,2], piece: {pieceType: null, pieceImgPath: null}},
    {position: [11,3], piece: {pieceType: null, pieceImgPath: null}},
    {position: [11,4], piece: {pieceType: null, pieceImgPath: null}},
    {position: [11,5], piece: {pieceType: null, pieceImgPath: null}},
    {position: [11,6], piece: {pieceType: null, pieceImgPath: null}} ],
};